defaults:
    - _self_
    - agent: cmcgs
    - override hydra/hydra_logging: disabled  
    - override hydra/job_logging: disabled

env_name: "2d-navigation-circles"
save_video: false
save_exploration: false
use_wandb: false
seed: 0

run_suffix: "test"
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .
